import os
import re
import logging
import urllib.request
import urllib.parse
from typing import Optional, Tuple
from urllib.parse import parse_qs, urlparse

logger = logging.getLogger("rabbithole.transcriber")

YOUTUBE_ID_RE = re.compile(r'^[A-Za-z0-9_-]{11}$')

# Exported via a browser extension (e.g. "Get cookies.txt LOCALLY") and dropped
# into the persistent data volume. Optional — only used if present, to get
# yt-dlp past YouTube's "Sign in to confirm you're not a bot" wall.
YOUTUBE_COOKIES_PATH = os.environ.get("YOUTUBE_COOKIES_PATH", "/app/data/youtube_cookies.txt")


def _authenticated_session():
    """A requests.Session carrying the exported YouTube cookies, if present."""
    import http.cookiejar
    import requests

    session = requests.Session()
    if os.path.isfile(YOUTUBE_COOKIES_PATH):
        jar = http.cookiejar.MozillaCookieJar(YOUTUBE_COOKIES_PATH)
        jar.load(ignore_discard=True, ignore_expires=True)
        session.cookies.update(jar)
    return session


def _scratch_cookiefile() -> Optional[str]:
    """
    A disposable copy of the master cookie file for yt-dlp to use.

    yt-dlp treats `cookiefile` as read-write and rewrites it after every run —
    and its writer silently drops HttpOnly cookies, which is exactly the auth
    cookies (SID, APISID, SAPISID, LOGIN_INFO, __Secure-1PSID, ...) that make
    the session logged-in. Handing it the master file corrupts it within one
    call. Copy to a throwaway temp path each time instead.
    """
    if not os.path.isfile(YOUTUBE_COOKIES_PATH):
        return None
    import shutil
    import tempfile
    fd, path = tempfile.mkstemp(suffix=".txt", prefix="ytcookies_")
    os.close(fd)
    shutil.copyfile(YOUTUBE_COOKIES_PATH, path)
    return path


BGUTIL_POT_BASE_URL = os.environ.get("BGUTIL_POT_BASE_URL", "http://bgutil-provider:4416")


def _ydl_opts(cookiefile: Optional[str] = None, **extra) -> dict:
    # remote_components pulls yt-dlp's JS challenge-solver script (run via the
    # Deno runtime baked into the image) — without it YouTube's "n" signature
    # challenge can't be solved and only image formats resolve.
    #
    # extractor_args wires in the bgutil PO-token sidecar (docker-compose
    # service `bgutil-provider`) — plain cookies aren't enough for
    # age-restricted/gated videos, which YouTube responds to with
    # LOGIN_REQUIRED regardless of cookie validity unless a PO token
    # (proof-of-origin, generated by solving YouTube's BotGuard challenge)
    # accompanies the request.
    opts = {
        "skip_download": True,
        "quiet": True,
        "no_warnings": True,
        "remote_components": {"ejs:github"},
        "extractor_args": {
            "youtubepot-bgutilhttp": {"base_url": [BGUTIL_POT_BASE_URL]},
        },
        **extra,
    }
    if cookiefile:
        opts["cookiefile"] = cookiefile
    return opts


def extract_video_id(url: str) -> Optional[str]:
    parsed = urlparse(url.strip())
    host = parsed.netloc.lower().removeprefix("www.")
    path_parts = [part for part in parsed.path.split("/") if part]

    candidate = None
    if host == "youtu.be" and path_parts:
        candidate = path_parts[0]
    elif host in {"youtube.com", "m.youtube.com", "music.youtube.com"}:
        if parsed.path == "/watch":
            candidate = parse_qs(parsed.query).get("v", [None])[0]
        elif len(path_parts) >= 2 and path_parts[0] in {"shorts", "embed", "live"}:
            candidate = path_parts[1]

    if candidate and YOUTUBE_ID_RE.fullmatch(candidate):
        return candidate
    return None


def normalize_url(url: str) -> str:
    """
    Normalize any YouTube URL variant to https://www.youtube.com/watch?v=VIDEO_ID
    Strips si, feature, pp, list, index, t and other tracking/playlist params.
    """
    video_id = extract_video_id(url)
    if video_id:
        return f"https://www.youtube.com/watch?v={video_id}"
    return url


def _classify_error(raw: str) -> str:
    low = raw.lower()
    if "sign in to confirm" in low or "not a bot" in low:
        return "YouTube is temporarily blocking automated requests from this IP (bot-check). Usually clears on its own — wait a while before retrying rather than retrying repeatedly, which extends the block."
    if "blocking requests from your ip" in low:
        return "YouTube rate-limited this IP for the caption API. Wait a while before retrying."
    # First line only — tracebacks and yt-dlp's multi-paragraph messages are noise in a UI badge.
    first_line = raw.strip().splitlines()[0] if raw.strip() else raw
    return first_line[:300]


def get_transcript(url: str) -> Tuple[Optional[str], Optional[str], Optional[str], Optional[str]]:
    """
    Returns (transcript_text, title, channel, error_reason).
    error_reason is only set when transcript_text is None — a short,
    human-readable explanation of why every strategy failed.
    Normalizes URL first, then tries youtube-transcript-api, then yt-dlp, then Whisper.
    """
    url = normalize_url(url)
    video_id = extract_video_id(url)
    if not video_id:
        logger.error(f"Could not extract video ID from: {url}")
        return None, None, None, "Could not parse a video ID from this URL"

    last_error = "Unknown error"

    # Strategy 1: youtube-transcript-api (v1.x instance API — no more classmethods)
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
        fetched = YouTubeTranscriptApi(http_client=_authenticated_session()).fetch(
            video_id, languages=["en", "en-US", "en-GB"]
        )
        text = " ".join(s.text for s in fetched)
        text = re.sub(r'\s+', ' ', text).strip()
        title, channel = _get_metadata(url)
        logger.info(f"[{video_id}] Transcript via youtube-transcript-api ({len(text)} chars)")
        return text, title, channel, None
    except Exception as e:
        logger.warning(f"[{video_id}] youtube-transcript-api failed: {e}")
        last_error = str(e)

    # Strategy 2: yt-dlp with existing (creator or auto-generated) captions
    title, channel = None, None
    cookiefile = _scratch_cookiefile()
    try:
        import yt_dlp
        with yt_dlp.YoutubeDL(_ydl_opts(cookiefile=cookiefile)) as ydl:
            info = ydl.extract_info(url, download=False)
            title = info.get("title")
            channel = info.get("uploader") or info.get("channel")

            all_subs = {}
            all_subs.update(info.get("subtitles") or {})
            all_subs.update(info.get("automatic_captions") or {})

            for lang in ["en", "en-US", "en-orig"]:
                if lang in all_subs:
                    for fmt in all_subs[lang]:
                        if fmt.get("ext") in ("vtt", "json3"):
                            try:
                                with urllib.request.urlopen(fmt["url"], timeout=15) as resp:
                                    raw = resp.read().decode("utf-8")
                                text = _parse_vtt(raw) if fmt["ext"] == "vtt" else _parse_json3(raw)
                                if text:
                                    logger.info(f"[{video_id}] Transcript via yt-dlp ({lang}, {fmt['ext']})")
                                    return text, title, channel, None
                            except Exception as sub_e:
                                logger.warning(f"[{video_id}] Sub download failed: {sub_e}")
                                last_error = str(sub_e)

    except Exception as e:
        logger.error(f"[{video_id}] yt-dlp caption lookup failed: {e}")
        last_error = str(e)
    finally:
        if cookiefile:
            os.unlink(cookiefile)

    # Strategy 3: no captions exist at all — transcribe the audio with Whisper
    text, whisper_error = _transcribe_with_whisper(url, video_id)
    if text:
        return text, title, channel, None
    if whisper_error:
        last_error = whisper_error

    if title is None:
        title, channel = _get_metadata(url)
    return None, title, channel, _classify_error(last_error)


def _get_metadata(url: str) -> Tuple[Optional[str], Optional[str]]:
    cookiefile = _scratch_cookiefile()
    try:
        import yt_dlp
        with yt_dlp.YoutubeDL(_ydl_opts(cookiefile=cookiefile)) as ydl:
            info = ydl.extract_info(url, download=False)
            return info.get("title"), info.get("uploader") or info.get("channel")
    except Exception:
        return None, None
    finally:
        if cookiefile:
            os.unlink(cookiefile)


WHISPER_MODEL = os.environ.get("WHISPER_MODEL", "base")
_whisper_model = None


def _get_whisper_model():
    global _whisper_model
    if _whisper_model is None:
        from faster_whisper import WhisperModel
        logger.info(f"Loading Whisper model '{WHISPER_MODEL}' (first use, may take a moment)")
        _whisper_model = WhisperModel(WHISPER_MODEL, device="cpu", compute_type="int8")
    return _whisper_model


def _transcribe_with_whisper(url: str, video_id: str) -> Tuple[Optional[str], Optional[str]]:
    """Downloads audio only and runs local speech-to-text — last-resort path
    for videos with no creator or auto-generated captions at all.
    Returns (text, error_message)."""
    import shutil
    import tempfile

    cookiefile = _scratch_cookiefile()
    tmp_dir = tempfile.mkdtemp(prefix="ytaudio_")
    try:
        import yt_dlp
        audio_path = os.path.join(tmp_dir, f"{video_id}.mp3")
        opts = _ydl_opts(
            cookiefile=cookiefile,
            format="bestaudio/best",
            outtmpl=os.path.join(tmp_dir, "%(id)s.%(ext)s"),
            postprocessors=[{
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "64",
            }],
        )
        opts["skip_download"] = False
        with yt_dlp.YoutubeDL(opts) as ydl:
            ydl.extract_info(url, download=True)

        if not os.path.isfile(audio_path):
            logger.warning(f"[{video_id}] Whisper: no audio file produced")
            return None, "Audio download produced no file"

        model = _get_whisper_model()
        segments, _info = model.transcribe(audio_path, language="en")
        text = " ".join(seg.text.strip() for seg in segments)
        text = re.sub(r'\s+', ' ', text).strip()
        if text:
            logger.info(f"[{video_id}] Transcript via Whisper ({len(text)} chars)")
            return text, None
        return None, "Whisper produced no speech (silent or non-English audio?)"

    except Exception as e:
        logger.error(f"[{video_id}] Whisper transcription failed: {e}")
        return None, str(e)
    finally:
        if cookiefile:
            os.unlink(cookiefile)
        shutil.rmtree(tmp_dir, ignore_errors=True)


def _parse_vtt(vtt: str) -> str:
    lines = []
    for line in vtt.split("\n"):
        line = line.strip()
        if not line or "-->" in line or line.startswith("WEBVTT") or line.isdigit():
            continue
        clean = re.sub(r'<[^>]+>', '', line)
        if clean:
            lines.append(clean)
    return " ".join(lines)


def _parse_json3(raw: str) -> str:
    import json
    try:
        data = json.loads(raw)
        words = []
        for event in data.get("events", []):
            for seg in event.get("segs", []):
                words.append(seg.get("utf8", ""))
        return re.sub(r'\s+', ' ', "".join(words)).strip()
    except Exception:
        return ""


LOCAL_VIDEO_EXTENSIONS = {
    ".mp4", ".mov", ".mkv", ".avi", ".webm", ".m4v",
    ".ts", ".wmv", ".flv", ".mpg", ".mpeg",
}

# Where browser-uploaded videos land before transcription. Each upload gets
# its own uuid subfolder (so the original filename survives untouched),
# and the whole subfolder is deleted once transcription finishes.
UPLOADS_DIR = "/app/data/uploads"


def is_uploaded_file_path(raw: str) -> bool:
    return (raw or "").startswith(UPLOADS_DIR + os.sep)

# Windows drive-letter path: C:\... or C:/...
_DRIVE_LETTER_RE = re.compile(r'^[A-Za-z]:[\\/]')
# UNC path: \\host\share\...
_UNC_RE = re.compile(r'^\\\\[^\\/]+\\[^\\/]+')
_SMB_URI_RE = re.compile(r'^smb://', re.IGNORECASE)


def strip_wrapping_quotes(raw: str) -> str:
    """Windows Explorer's "Copy as path" wraps the result in double quotes —
    strip those (or single quotes) if present, so pasted paths just work."""
    raw = (raw or "").strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ('"', "'"):
        raw = raw[1:-1].strip()
    return raw


def is_smb_video_path(raw: str) -> bool:
    """True if `raw` looks like a Windows drive-letter path, a UNC path, or
    an smb:// URI pointing at a video file — i.e. something we should fetch
    over SMB rather than treat as a YouTube/Reddit URL."""
    raw = strip_wrapping_quotes(raw)
    if not raw:
        return False
    ext = os.path.splitext(raw)[1].lower()
    if ext not in LOCAL_VIDEO_EXTENSIONS:
        return False
    return bool(_DRIVE_LETTER_RE.match(raw) or _UNC_RE.match(raw) or _SMB_URI_RE.match(raw))


def parse_smb_path(raw: str, default_host: str = None) -> Tuple[str, str, str]:
    """
    Parse a drive-letter path, UNC path, or smb:// URI into (host, share, rel_path).
    A bare drive-letter path (C:\\...) has no host of its own — it's resolved
    against `default_host` (the "Default SMB Host" in Settings) using the
    Windows admin share convention (C: -> C$).
    Raises ValueError with a human-readable reason if it can't be resolved.
    """
    raw = strip_wrapping_quotes(raw)

    if _SMB_URI_RE.match(raw):
        rest = raw[len("smb://"):]
        parts = [p for p in rest.split("/") if p]
        if len(parts) < 2:
            raise ValueError("smb:// URI must include a host and a share")
        host, share = parts[0], parts[1]
        rel_path = "\\".join(parts[2:])
    elif _UNC_RE.match(raw):
        parts = [p for p in raw.split("\\") if p]
        if len(parts) < 2:
            raise ValueError("UNC path must include a host and a share")
        host, share = parts[0], parts[1]
        rel_path = "\\".join(parts[2:])
    elif _DRIVE_LETTER_RE.match(raw):
        if not default_host:
            raise ValueError(
                "This is a local drive-letter path — set a \"Default SMB Host\" "
                "in Settings (the IP of the machine this file lives on), or "
                "paste the full \\\\host\\share\\... path instead"
            )
        drive = raw[0].upper()
        host = default_host
        share = f"{drive}$"
        rel_path = raw[2:].lstrip("\\/").replace("/", "\\")
    else:
        raise ValueError("Not a recognized local, UNC, or smb:// video path")

    if not rel_path:
        raise ValueError("Path has a host/share but no file")
    return host, share, rel_path


def title_from_filename(path: str) -> str:
    """Derive a display title from either a POSIX or Windows-style path."""
    name = re.split(r'[\\/]', path)[-1]
    name = os.path.splitext(name)[0]
    name = re.sub(r"[._]+", " ", name).strip()
    return name or "Untitled"


def parent_folder_name(path: str) -> Optional[str]:
    """Name of the immediate containing folder, from either path style."""
    parts = [p for p in re.split(r'[\\/]', path) if p]
    return parts[-2] if len(parts) >= 2 else None


def _smb_session_kwargs(smb_cfg: dict) -> dict:
    # smbclient.register_session() has no `domain` parameter — NTLM domain
    # is expressed by prefixing the username as "DOMAIN\\user" instead.
    username = smb_cfg.get("username") or None
    domain = smb_cfg.get("domain") or None
    if username and domain and "\\" not in username and "@" not in username:
        username = f"{domain}\\{username}"
    return {
        "username": username,
        "password": smb_cfg.get("password") or None,
        "port": int(smb_cfg.get("port") or 445),
    }


def smb_file_exists(host: str, share: str, rel_path: str, smb_cfg: dict) -> bool:
    import smbclient
    smbclient.register_session(host, **_smb_session_kwargs(smb_cfg))
    unc = f"\\\\{host}\\{share}\\{rel_path}"
    return smbclient.path.isfile(unc)


def fetch_smb_file(host: str, share: str, rel_path: str, smb_cfg: dict, dest_dir: str) -> str:
    """
    Downloads a file from an SMB share into a local temp file inside
    `dest_dir`. Returns the local path. Caller is responsible for cleaning
    up `dest_dir` once done (transcription reads it, then it's discarded).
    """
    import shutil
    import tempfile
    import smbclient

    smbclient.register_session(host, **_smb_session_kwargs(smb_cfg))
    unc = f"\\\\{host}\\{share}\\{rel_path}"
    ext = os.path.splitext(rel_path)[1] or ".mp4"
    fd, local_path = tempfile.mkstemp(suffix=ext, prefix="rh_smb_", dir=dest_dir)
    os.close(fd)
    with smbclient.open_file(unc, mode="rb") as remote_f, open(local_path, "wb") as local_f:
        shutil.copyfileobj(remote_f, local_f, length=4 * 1024 * 1024)
    return local_path


def transcribe_local_file(path: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Runs local Whisper speech-to-text directly on a video file on disk
    (faster-whisper decodes audio from the container via PyAV, so no
    separate audio-extraction step is needed). Returns (text, error_message).
    """
    try:
        model = _get_whisper_model()
        segments, _info = model.transcribe(path, language="en")
        text = " ".join(seg.text.strip() for seg in segments)
        text = re.sub(r'\s+', ' ', text).strip()
        if text:
            logger.info(f"[{path}] Transcript via Whisper ({len(text)} chars)")
            return text, None
        return None, "Whisper produced no speech (silent or non-English audio?)"
    except Exception as e:
        logger.error(f"[{path}] Local Whisper transcription failed: {e}")
        return None, str(e)


def truncate_transcript(text: str, max_chars: int = 14000) -> str:
    if len(text) <= max_chars:
        return text
    half = max_chars // 2
    return text[:half] + "\n\n[...transcript truncated...]\n\n" + text[-(max_chars - half):]
